// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2xSRGMCr50PLNRqRe8UCTbOWeov_jehI',
    appId: '1:1039708756425:web:81ce42457d04930de9b018',
    messagingSenderId: '1039708756425',
    projectId: 'notes-72713',
    authDomain: 'notes-72713.firebaseapp.com',
    storageBucket: 'notes-72713.firebasestorage.app',
    measurementId: 'G-S0DQ6EVXEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4_dS1HIle-ke0297JkW2qeFNplehfcMs',
    appId: '1:1039708756425:android:a84149db0facdec4e9b018',
    messagingSenderId: '1039708756425',
    projectId: 'notes-72713',
    storageBucket: 'notes-72713.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo4l1-liBZSFfEQS9hmPQWQtXqyCe0mIs',
    appId: '1:1039708756425:ios:b6a2009701fc94cde9b018',
    messagingSenderId: '1039708756425',
    projectId: 'notes-72713',
    storageBucket: 'notes-72713.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo4l1-liBZSFfEQS9hmPQWQtXqyCe0mIs',
    appId: '1:1039708756425:ios:b6a2009701fc94cde9b018',
    messagingSenderId: '1039708756425',
    projectId: 'notes-72713',
    storageBucket: 'notes-72713.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2xSRGMCr50PLNRqRe8UCTbOWeov_jehI',
    appId: '1:1039708756425:web:fb11e54513c3a50ce9b018',
    messagingSenderId: '1039708756425',
    projectId: 'notes-72713',
    authDomain: 'notes-72713.firebaseapp.com',
    storageBucket: 'notes-72713.firebasestorage.app',
    measurementId: 'G-3Q2F3J4R8R',
  );
}
