// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvbo33sn7W2jqmJZE6i235HSQM51ocix4',
    appId: '1:654467022420:web:4de614df3bcbb2a9e4b7c1',
    messagingSenderId: '654467022420',
    projectId: 'daftarbelanja-53798',
    authDomain: 'daftarbelanja-53798.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-53798-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-53798.firebasestorage.app',
    measurementId: 'G-7MSR0VE0LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe4V2pegdVMbxjWsvJGkT1qcI2clhmV5I',
    appId: '1:654467022420:android:94a5d37617a2e417e4b7c1',
    messagingSenderId: '654467022420',
    projectId: 'daftarbelanja-53798',
    databaseURL: 'https://daftarbelanja-53798-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-53798.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6EdM62n3wTIANgXlIT-fCixsIvU--DsI',
    appId: '1:654467022420:ios:1be65bc731d69a39e4b7c1',
    messagingSenderId: '654467022420',
    projectId: 'daftarbelanja-53798',
    databaseURL: 'https://daftarbelanja-53798-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-53798.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6EdM62n3wTIANgXlIT-fCixsIvU--DsI',
    appId: '1:654467022420:ios:1be65bc731d69a39e4b7c1',
    messagingSenderId: '654467022420',
    projectId: 'daftarbelanja-53798',
    databaseURL: 'https://daftarbelanja-53798-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-53798.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvbo33sn7W2jqmJZE6i235HSQM51ocix4',
    appId: '1:654467022420:web:37abec142ab222cde4b7c1',
    messagingSenderId: '654467022420',
    projectId: 'daftarbelanja-53798',
    authDomain: 'daftarbelanja-53798.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-53798-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-53798.firebasestorage.app',
    measurementId: 'G-YXBFMVFRTS',
  );
}
