// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD6NhBul19n73c8JP-DPr6_wvkyGd3tbc',
    appId: '1:1098784686358:web:22f92073d78dda631e1037',
    messagingSenderId: '1098784686358',
    projectId: 'mdpgold-cb723',
    authDomain: 'mdpgold-cb723.firebaseapp.com',
    databaseURL: 'https://mdpgold-cb723-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-cb723.firebasestorage.app',
    measurementId: 'G-02KSLVQXDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIn1z5URFZdCD_pbifYjd0drsU6AAq21M',
    appId: '1:1098784686358:android:91daf78e0945bdd21e1037',
    messagingSenderId: '1098784686358',
    projectId: 'mdpgold-cb723',
    databaseURL: 'https://mdpgold-cb723-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-cb723.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD96HhTR-30kyMDFN77b5T9TCL9trU5NLs',
    appId: '1:1098784686358:ios:93f8f2ce10a6a5b01e1037',
    messagingSenderId: '1098784686358',
    projectId: 'mdpgold-cb723',
    databaseURL: 'https://mdpgold-cb723-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-cb723.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD96HhTR-30kyMDFN77b5T9TCL9trU5NLs',
    appId: '1:1098784686358:ios:93f8f2ce10a6a5b01e1037',
    messagingSenderId: '1098784686358',
    projectId: 'mdpgold-cb723',
    databaseURL: 'https://mdpgold-cb723-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-cb723.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD6NhBul19n73c8JP-DPr6_wvkyGd3tbc',
    appId: '1:1098784686358:web:90b7173800be3ffb1e1037',
    messagingSenderId: '1098784686358',
    projectId: 'mdpgold-cb723',
    authDomain: 'mdpgold-cb723.firebaseapp.com',
    databaseURL: 'https://mdpgold-cb723-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-cb723.firebasestorage.app',
    measurementId: 'G-E992RMLN1X',
  );
}
